# Schwabot Vector Settings Experiment Configuration
# Extended integration with settings controller, vector validator, and matrix allocator

# Mathematical Flow Parameters
mathematical_flow:
  entropy_threshold: 0.75
  fractal_dimension: 1.5
  quantum_drift_factor: 0.25
  vector_confidence_min: 0.6
  matrix_basket_size: 16
  tick_sync_interval: 3.75
  volume_delta_threshold: 0.1
  hash_confidence_decay: 0.95
  ghost_strategy_weight: 0.3
  backlog_retention_cycles: 1000

# Reinforcement Learning Parameters
reinforcement_learning:
  learning_rate: 0.01
  failure_penalty_weight: 0.5
  success_reward_weight: 1.0
  exploration_rate: 0.1
  memory_size: 10000
  batch_size: 32
  update_frequency: 100
  convergence_threshold: 0.001
  max_iterations: 1000
  adaptive_learning: true

# Vector Validation Rules
vector_validation_rules:
  entropy_threshold: 0.75
  fractal_dimension_range: [1.0, 2.0]
  quantum_coherence_min: 0.6
  vector_magnitude_range: [0.1, 10.0]
  angular_momentum_threshold: 0.5
  phase_alignment_min: 0.7
  stability_index_min: 0.8
  convergence_rate_min: 0.01
  max_validation_errors: 3
  confidence_threshold: 0.6

# Matrix Allocation Strategies
matrix_allocation_strategies:
  risk_parity:
    enabled: true
    risk_budget: 0.2
    rebalance_frequency: 50
    optimization_weight: 0.4
    
  max_sharpe:
    enabled: true
    risk_free_rate: 0.02
    rebalance_frequency: 50
    optimization_weight: 0.3
    
  equal_weight:
    enabled: true
    rebalance_frequency: 100
    optimization_weight: 0.2
    
  performance_weighted:
    enabled: true
    performance_window: 100
    rebalance_frequency: 50
    optimization_weight: 0.1

# Demo Backtesting Integration
demo_backtesting:
  enabled: true
  integration_mode: "full"
  
  # Vector validation in backtesting
  vector_validation_in_backtest: true
  validation_timeout: 5.0
  auto_reject_invalid_vectors: true
  validation_history_tracking: true
  
  # Matrix allocation in backtesting
  matrix_allocation_in_backtest: true
  auto_rebalance_during_backtest: true
  allocation_optimization_frequency: 100
  performance_tracking: true
  
  # Settings controller integration
  settings_controller_integration: true
  parameter_adaptation: true
  learning_from_backtest_results: true
  failure_analysis: true

# Vector Experiment Configurations
vector_experiments:
  experiment_1:
    name: "High Entropy Vectors"
    description: "Testing vectors with high entropy scores"
    parameters:
      entropy_threshold: 0.8
      fractal_dimension: 1.8
      quantum_drift_factor: 0.3
      vector_confidence_min: 0.7
    expected_outcomes:
      - "Higher volatility"
      - "Increased exploration"
      - "Potential for higher returns"
    risk_level: "high"
    
  experiment_2:
    name: "Low Risk Vectors"
    description: "Testing vectors with conservative parameters"
    parameters:
      entropy_threshold: 0.6
      fractal_dimension: 1.2
      quantum_drift_factor: 0.15
      vector_confidence_min: 0.8
    expected_outcomes:
      - "Lower volatility"
      - "Stable performance"
      - "Consistent returns"
    risk_level: "low"
    
  experiment_3:
    name: "Balanced Vectors"
    description: "Testing vectors with balanced parameters"
    parameters:
      entropy_threshold: 0.75
      fractal_dimension: 1.5
      quantum_drift_factor: 0.25
      vector_confidence_min: 0.6
    expected_outcomes:
      - "Moderate volatility"
      - "Balanced risk-reward"
      - "Adaptive performance"
    risk_level: "medium"

# Matrix Basket Configurations
matrix_baskets:
  conservative_basket:
    name: "Conservative Matrix Basket"
    description: "Low-risk matrix allocation"
    total_capacity: 10000.0
    risk_budget: 0.15
    return_target: 0.08
    optimization_strategy: "risk_parity"
    matrices:
      - matrix_id: "conservative_matrix_1"
        allocation_percentage: 0.4
        risk_level: 0.2
        expected_return: 0.06
        volatility: 0.10
      - matrix_id: "conservative_matrix_2"
        allocation_percentage: 0.3
        risk_level: 0.3
        expected_return: 0.08
        volatility: 0.15
      - matrix_id: "conservative_matrix_3"
        allocation_percentage: 0.3
        risk_level: 0.25
        expected_return: 0.07
        volatility: 0.12
        
  aggressive_basket:
    name: "Aggressive Matrix Basket"
    description: "High-risk, high-reward matrix allocation"
    total_capacity: 10000.0
    risk_budget: 0.35
    return_target: 0.20
    optimization_strategy: "max_sharpe"
    matrices:
      - matrix_id: "aggressive_matrix_1"
        allocation_percentage: 0.5
        risk_level: 0.6
        expected_return: 0.25
        volatility: 0.35
      - matrix_id: "aggressive_matrix_2"
        allocation_percentage: 0.3
        risk_level: 0.5
        expected_return: 0.18
        volatility: 0.28
      - matrix_id: "aggressive_matrix_3"
        allocation_percentage: 0.2
        risk_level: 0.4
        expected_return: 0.15
        volatility: 0.22

# Performance Monitoring Configuration
performance_monitoring:
  enabled: true
  metrics_tracking: true
  real_time_analysis: true
  
  # Vector performance metrics
  vector_metrics:
    track_entropy_scores: true
    track_fractal_dimensions: true
    track_quantum_coherence: true
    track_validation_success_rate: true
    track_confidence_scores: true
    
  # Matrix performance metrics
  matrix_metrics:
    track_allocation_efficiency: true
    track_risk_adjusted_returns: true
    track_diversification_scores: true
    track_rebalance_frequency: true
    track_optimization_effectiveness: true
    
  # Overall system metrics
  system_metrics:
    track_overall_performance: true
    track_learning_progress: true
    track_parameter_adaptation: true
    track_failure_analysis: true
    track_success_patterns: true

# Integration Testing Scenarios
integration_testing:
  enabled: true
  test_frequency: 1800  # 30 minutes
  
  # Component integration tests
  component_tests:
    settings_controller_integration: true
    vector_validator_integration: true
    matrix_allocator_integration: true
    demo_system_integration: true
    
  # End-to-end test scenarios
  end_to_end_scenarios:
    - "full_backtest_with_validation"
    - "parameter_optimization_cycle"
    - "matrix_allocation_optimization"
    - "reinforcement_learning_cycle"
    - "performance_analysis_cycle"

# Data Management and Storage
data_management:
  # Vector data storage
  vector_data:
    storage_enabled: true
    storage_format: "json"
    compression_enabled: true
    retention_period: 30  # days
    backup_frequency: 86400  # 24 hours
    
  # Matrix data storage
  matrix_data:
    storage_enabled: true
    storage_format: "json"
    compression_enabled: true
    retention_period: 30  # days
    backup_frequency: 86400  # 24 hours
    
  # Performance data storage
  performance_data:
    storage_enabled: true
    storage_format: "json"
    compression_enabled: true
    retention_period: 90  # days
    backup_frequency: 86400  # 24 hours

# Reporting and Analytics
reporting:
  enabled: true
  report_frequency: 3600  # 1 hour
  
  # Report types
  report_types:
    vector_validation_reports: true
    matrix_allocation_reports: true
    performance_analysis_reports: true
    integration_test_reports: true
    learning_progress_reports: true
    
  # Export formats
  export_formats:
    - "json"
    - "csv"
    - "html"
    - "pdf"
    - "markdown"

# Advanced Configuration
advanced_configuration:
  # Machine learning integration
  ml_integration:
    enabled: true
    models:
      - "vector_optimization"
      - "matrix_allocation"
      - "risk_assessment"
      - "performance_prediction"
    
  # AI consensus system
  ai_consensus:
    enabled: true
    consensus_threshold: 0.7
    ai_models_count: 3
    consensus_weight: 0.8
    
  # Quantum simulation (experimental)
  quantum_simulation:
    enabled: false
    quantum_bits: 8
    quantum_circuits: 4
    simulation_depth: 10

# Emergency and Safety Configuration
emergency_configuration:
  enabled: true
  
  # Safety thresholds
  safety_thresholds:
    max_risk_score: 0.5
    max_drawdown: 0.2
    min_confidence_score: 0.3
    max_validation_errors: 5
    
  # Emergency procedures
  emergency_procedures:
    auto_stop_on_threshold_breach: true
    fallback_to_conservative_settings: true
    emergency_recovery_mode: true
    alert_on_emergency: true

# Logging and Debugging
logging:
  level: "INFO"
  file_logging: true
  console_logging: true
  log_rotation: true
  max_log_size: "100MB"
  log_retention: 30  # days
  
  # Component-specific logging
  component_logging:
    settings_controller: "INFO"
    vector_validator: "INFO"
    matrix_allocator: "INFO"
    demo_system: "INFO"
    performance_monitoring: "INFO"

# System Health Monitoring
system_health:
  enabled: true
  health_check_frequency: 300  # 5 minutes
  
  # Health metrics
  health_metrics:
    cpu_usage_threshold: 0.8
    memory_usage_threshold: 0.8
    disk_usage_threshold: 0.9
    response_time_threshold: 5.0  # seconds
    
  # Component health tracking
  component_health:
    settings_controller_health: true
    vector_validator_health: true
    matrix_allocator_health: true
    demo_system_health: true

# Last updated timestamp
last_updated: "2024-01-01T00:00:00Z"
version: "2.0.0"
description: "Extended vector settings experiment configuration with full integration support" 