# Schwabot Pre-commit Configuration
# =================================
# Automated code quality checks that run before each commit

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: [--fix=lf]

  # Custom hooks
  - repo: local
    hooks:
      - id: no-null-bytes
        name: "Reject files containing ASCII NUL (\x00)"
        entry: python -c "import sys, pathlib; bad=[str(p) for p in pathlib.Path('.').rglob('*.py') if b'\0' in p.read_bytes()]; print('\n'.join(bad)); sys.exit(bool(bad))"
        language: system
        types: [python]

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=100, --target-version=py311]

  # Import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # Flake8 linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --ignore=E203,W503]
        additional_dependencies:
          - flake8-docstrings
          - flake8-import-order
          - flake8-bugbear

  # Type checking with mypy (optional - can be slow)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --check-untyped-defs]
        additional_dependencies:
          - types-all

  # Python upgrade opportunities
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # Remove unused imports
  - repo: https://github.com/pycqa/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports

  # Security scanning with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  # Additional custom hook for pylint
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: 
          - "-rn"
          - "-sn"
          - "--load-plugins=pylint.extensions.docparams"
          - "--disable=C0111,R0903,W0311"

# Configuration for ci (optional)
ci:
  autofix_commit_msg: "style: auto-fix code style issues"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: true
  autoupdate_schedule: weekly
  skip: [mypy]  # Skip mypy in CI (run manually) 