# Ferris RDE Daemon Configuration
# Configuration file for 24/7 Ferris RDE trading daemon

# Core Daemon Settings
daemon:
  name: "FerrisRDE"
  version: "1.0.0"
  enabled: true
  log_level: "INFO"
  log_file: "logs/ferris_rde_daemon.log"
  pid_file: "logs/ferris_rde_daemon.pid"

# Trading Configuration
trading:
  enabled: true
  paper_trading: true  # Set to false for live trading
  max_concurrent_trades: 10
  risk_management_enabled: true
  
  # Position sizing
  max_position_size: 0.25  # Maximum 25% of portfolio per trade
  default_position_size: 0.05  # Default 5% of portfolio per trade
  
  # Risk limits
  max_daily_loss: 0.02  # Maximum 2% daily loss
  max_drawdown: 0.10  # Maximum 10% drawdown
  stop_loss_percentage: 0.02  # 2% stop loss
  take_profit_percentage: 0.04  # 4% take profit

# Processing Configuration
processing:
  enable_gpu: true
  enable_distributed: false
  bit_depth_range: [2, 42]
  max_workers: 10
  
  # Performance tuning
  tick_interval_seconds: 1.0
  batch_size: 100
  memory_limit_mb: 1024

# Timing Configuration
timing:
  tick_interval_seconds: 1.0
  health_check_interval_seconds: 30.0
  performance_report_interval_seconds: 300.0  # 5 minutes
  mathematical_update_interval_seconds: 5.0
  error_report_interval_seconds: 60.0

# Asset Configuration
assets:
  primary:
    - "BTC/USD"
    - "ETH/USD"
  
  secondary:
    - "XRP/USD"
    - "ADA/USD"
    - "DOT/USD"
    - "LINK/USD"
  
  # Asset-specific settings
  btc_usd:
    min_confidence: 0.7
    max_position_size: 0.3
    volatility_threshold: 0.15
  
  eth_usd:
    min_confidence: 0.65
    max_position_size: 0.25
    volatility_threshold: 0.12

# Ferris RDE Configuration
ferris_rde:
  enabled: true
  cycle_duration_minutes: 60
  
  # Phase transitions
  phase_transitions:
    tick_to_pivot: 0.8
    pivot_to_ascent: 0.7
    ascent_to_descent: 0.6
    descent_to_tick: 0.9
  
  # Performance thresholds
  momentum_threshold: 0.5
  volatility_threshold: 0.3
  confidence_threshold: 0.6
  
  # Cycle management
  cycle_timeout: 7200  # 2 hours
  auto_reset_enabled: true
  max_history_size: 100

# Mathematical Framework Configuration
mathematical:
  enable_quantum_thermal: true
  enable_void_well_metrics: true
  enable_kelly_criterion: true
  enable_recursive_time_lock: true
  
  # Ferris Wheel settings
  ferris_wheel:
    periods: [144, 288, 576]  # 1h, 2h, 4h
    harmonic_ratios: [1.0, 1.618, 2.618]
    coherence_threshold: 0.7
  
  # Quantum Thermal settings
  quantum_thermal:
    base_temperature: 300.0  # Kelvin
    coupling_strength: 0.1
    decoherence_rate: 0.01
  
  # Void Well settings
  void_well:
    window_size: 20
    fractal_threshold: 0.5
    entropy_threshold: 0.3
  
  # Kelly Criterion settings
  kelly:
    safety_factor: 0.25
    max_fraction: 0.25
    win_probability_threshold: 0.6

# API Configuration
api:
  # CoinGecko
  coingecko:
    enabled: true
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 50  # requests per minute
    timeout: 10.0
  
  # CoinMarketCap
  coinmarketcap:
    enabled: true
    base_url: "https://pro-api.coinmarketcap.com/v1"
    rate_limit: 30  # requests per minute
    timeout: 10.0
  
  # CCXT (for order book data)
  ccxt:
    enabled: true
    exchange: "binance"
    timeout: 10.0
    rate_limit: 100  # requests per minute

# Monitoring Configuration
monitoring:
  enable_health_monitoring: true
  enable_performance_tracking: true
  enable_error_logging: true
  max_error_count: 1000
  
  # Health check thresholds
  health_thresholds:
    max_latency_ms: 1000
    min_success_rate: 0.95
    max_error_rate: 0.05
  
  # Performance thresholds
  performance_thresholds:
    max_processing_time_ms: 100
    min_throughput_ticks_per_second: 0.5
    max_memory_usage_mb: 2048

# Visualization Configuration
visualization:
  enable_visualization: true
  dashboard_port: 8080
  websocket_port: 8081
  
  # Web dashboard
  web_dashboard:
    enabled: true
    host: "0.0.0.0"
    port: 8080
    debug: false
  
  # API server
  api_server:
    enabled: true
    host: "0.0.0.0"
    port: 8081
    cors_enabled: true
  
  # Real-time updates
  real_time_updates:
    enabled: true
    websocket_path: "/ws"
    update_interval_seconds: 1.0

# Database Configuration
database:
  enabled: false  # Set to true if using database
  type: "sqlite"  # sqlite, postgresql, mysql
  
  # SQLite settings
  sqlite:
    database_file: "data/ferris_rde.db"
    backup_enabled: true
    backup_interval_hours: 24
  
  # PostgreSQL settings
  postgresql:
    host: "localhost"
    port: 5432
    database: "ferris_rde"
    username: "ferris_user"
    password: "secure_password"
    pool_size: 10

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File handlers
  file_handlers:
    main:
      filename: "logs/ferris_rde_daemon.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
    
    error:
      filename: "logs/ferris_rde_errors.log"
      max_bytes: 5242880  # 5MB
      backup_count: 3
    
    performance:
      filename: "logs/ferris_rde_performance.log"
      max_bytes: 5242880  # 5MB
      backup_count: 3
  
  # Console handler
  console:
    enabled: true
    level: "INFO"

# Security Configuration
security:
  # API keys (store securely in production)
  api_keys:
    coingecko: ""  # Optional for public API
    coinmarketcap: ""  # Required for pro API
  
  # Rate limiting
  rate_limiting:
    enabled: true
    max_requests_per_minute: 100
    burst_limit: 20
  
  # SSL/TLS
  ssl:
    enabled: false
    cert_file: ""
    key_file: ""

# Backup and Recovery
backup:
  enabled: true
  interval_hours: 24
  retention_days: 7
  backup_dir: "backups/"
  
  # What to backup
  backup_components:
    - "configuration"
    - "logs"
    - "metrics"
    - "mathematical_states"
    - "trade_history"

# Development and Testing
development:
  debug_mode: false
  test_mode: false
  
  # Mock data for testing
  mock_data:
    enabled: false
    price_volatility: 0.1
    volume_variation: 0.2
  
  # Performance profiling
  profiling:
    enabled: false
    profile_file: "profiles/ferris_rde_profile.prof"

# Advanced Configuration
advanced:
  # Memory management
  memory:
    gc_threshold: 0.8  # Garbage collection threshold
    max_memory_mb: 2048
    memory_check_interval_seconds: 60
  
  # Threading
  threading:
    max_workers: 10
    thread_timeout_seconds: 30
    deadlock_detection: true
  
  # Async settings
  async:
    max_concurrent_tasks: 50
    task_timeout_seconds: 30
    retry_attempts: 3
  
  # Mathematical optimization
  mathematical_optimization:
    enable_caching: true
    cache_size: 1000
    cache_ttl_seconds: 3600
    
    # GPU acceleration
    gpu_acceleration:
      enabled: true
      memory_limit_mb: 512
      batch_size: 64 