# Schwabot Live Trading Configuration
# ===================================
# Production configuration for live trading with 2-gram pattern detection
# and full system integration

# System Mode Configuration
system_mode: "live"  # demo, live, backtest
safe_mode: false
debug_mode: false

# Default Trading Parameters
default_symbol: "BTC/USDC"
# initial_capital will be auto-detected from exchange portfolio
max_position_size: 0.1  # 10% max position
stop_loss_pct: 0.02     # 2% stop loss
take_profit_pct: 0.04   # 4% take profit

# 2-Gram Detector Configuration
2gram_config:
  window_size: 100
  burst_threshold: 2.0
  similarity_threshold: 0.85
  t_cell_sensitivity: 0.7
  enable_fractal_memory: true
  pattern_memory_size: 1000
  health_check_interval: 30.0

# Strategy Router Configuration
strategy_router_config:
  execution_mode: "live"  # demo, live, backtest
  enable_phantom_integration: true
  enable_portfolio_rebalancing: true
  max_concurrent_triggers: 5
  trigger_cooldown: 5.0
  execution_priority_threshold: 5

# Trading Pipeline Configuration
trading_pipeline_config:
  symbol: "BTC/USDC"
  initial_capital: 10000.0
  risk_management:
    max_daily_loss: 0.05    # 5% max daily loss
    max_drawdown: 0.15      # 15% max drawdown
    volatility_threshold: 0.8
    correlation_threshold: 0.9
  strategy_branches:
    - "mean_reversion"
    - "momentum"
    - "arbitrage"
    - "scalping"
    - "swing"
    - "grid"
    - "ferris_wheel"

# Real-Time Execution Engine Configuration
execution_engine_config:
  market_monitoring_interval: 1.0
  signal_processing_interval: 0.5
  risk_monitoring_interval: 5.0
  performance_tracking_interval: 30.0
  position_management_interval: 10.0
  max_signals_per_minute: 60
  signal_cooldown: 2.0
  risk_limits:
    max_open_positions: 5
    max_daily_trades: 100
    max_position_value: 5000.0

# Entropy-Enhanced Trading Executor Configuration
entropy_executor_config:
  entropy_signal_enabled: true
  entropy_confidence_threshold: 0.7
  entropy_timing_cycles: [5, 15, 30, 60]  # seconds
  entropy_integration_weight: 0.3
  fractal_memory_enabled: true
  phantom_detection_enabled: true
  profit_cycle_allocation: true

# Portfolio Balancer Configuration
portfolio_balancer_config:
  rebalancing_strategy: "phantom_adaptive"
  rebalance_threshold: 0.5
  rebalance_interval: 3600.0  # 1 hour
  target_allocation:
    BTC: 0.4
    ETH: 0.3
    USDC: 0.3
  max_deviation: 0.2
  enable_dynamic_rebalancing: true

# BTC/USDC Trading Integration Configuration
btc_usdc_config:
  base_order_size: 0.01  # BTC
  max_order_size: 0.1    # BTC
  min_order_size: 0.001  # BTC
  max_daily_trades: 25
  max_daily_volume: 1.0  # BTC
  order_timeout: 30.0
  retry_attempts: 3
  slippage_tolerance: 0.001  # 0.1%

# Master Profit Coordination System Configuration
master_system_config:
  orchestrator_config:
    profit_threshold: 0.15
    risk_adjustment_factor: 0.8
    coordination_interval: 10.0
  resonance_config:
    wave_coherence_threshold: 0.65
    resonance_detection_enabled: true
    fractal_resonance_weight: 0.4
  integration_config:
    enable_2gram_integration: true
    enable_entropy_integration: true
    enable_fractal_integration: true
    enable_phantom_integration: true

# Exchange Configuration
exchanges:
  - name: "coinbase"
    enabled: true
    api_key_env: "COINBASE_API_KEY"
    secret_env: "COINBASE_SECRET"
    sandbox: false
    trading_pairs: ["BTC/USDC", "ETH/USDC"]
    rate_limit: 100  # requests per minute
    
  - name: "binance"
    enabled: true
    api_key_env: "BINANCE_API_KEY"
    secret_env: "BINANCE_SECRET"
    sandbox: false
    trading_pairs: ["BTC/USDC", "ETH/USDC"]
    rate_limit: 1200  # requests per minute
    
  - name: "kraken"
    enabled: true
    api_key_env: "KRAKEN_API_KEY"
    secret_env: "KRAKEN_SECRET"
    sandbox: false
    trading_pairs: ["BTC/USDC", "ETH/USDC"]
    rate_limit: 15  # requests per 15 seconds

# Market Data Configuration
market_data:
  sources:
    - "coinbase"
    - "binance"
    - "kraken"
  update_interval: 1.0
  history_length: 1000
  enable_order_book: true
  enable_trades: true
  enable_ohlcv: true

# Risk Management Configuration
risk_management:
  global_risk_limits:
    max_total_exposure: 0.8  # 80% of capital
    max_single_position: 0.2  # 20% of capital
    max_correlation: 0.7
    min_diversification: 3  # minimum positions
  
  position_risk_limits:
    max_holding_time: 86400  # 24 hours
    max_drawdown_per_position: 0.1  # 10%
    stop_loss_activation: 0.05  # 5%
    
  market_risk_limits:
    volatility_threshold: 0.8
    volume_threshold: 1000000  # minimum volume
    spread_threshold: 0.002  # maximum spread

# Performance Monitoring Configuration
performance_monitoring:
  metrics_tracking: true
  real_time_dashboard: true
  performance_logging: true
  alert_thresholds:
    drawdown_warning: 0.1  # 10%
    drawdown_critical: 0.2  # 20%
    profit_target: 0.05  # 5%
    loss_limit: 0.15  # 15%

# Logging Configuration
logging:
  level: "INFO"
  file_logging: true
  console_logging: true
  log_file: "logs/schwabot_live.log"
  max_file_size: "100MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Database Configuration
database:
  enabled: true
  type: "sqlite"  # sqlite, postgresql, mysql
  connection_string: "sqlite:///data/schwabot_live.db"
  backup_enabled: true
  backup_interval: 3600  # 1 hour

# Security Configuration
security:
  api_key_encryption: true
  secure_config_storage: true
  ip_whitelist: []
  session_timeout: 3600  # 1 hour
  max_login_attempts: 3

# Backup Configuration
backup:
  enabled: true
  backup_interval: 3600  # 1 hour
  backup_retention: 7  # days
  backup_location: "backups/"
  compression: true

# Development Configuration
development:
  debug_mode: false
  test_mode: false
  mock_exchanges: false
  performance_profiling: false
  memory_monitoring: true

# Integration Configuration
integrations:
  telegram_notifications:
    enabled: false
    bot_token: ""
    chat_id: ""
  
  email_notifications:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    recipients: []
  
  webhook_notifications:
    enabled: false
    webhook_url: ""
    events: ["trade_executed", "risk_alert", "system_error"]

# Advanced Configuration
advanced:
  # 2-gram specific settings
  two_gram_advanced:
    pattern_weight_decay: 0.95
    burst_score_smoothing: 0.8
    fractal_memory_retention: 1000
    t_cell_activation_threshold: 0.8
    health_score_decay: 0.99
    
  # Entropy specific settings
  entropy_advanced:
    signal_processing_window: 60
    confidence_calculation_method: "weighted_average"
    timing_cycle_optimization: true
    fractal_resonance_threshold: 0.7
    
  # Strategy specific settings
  strategy_advanced:
    adaptive_priority_scaling: true
    dynamic_risk_adjustment: true
    portfolio_correlation_analysis: true
    market_regime_detection: true 

# CCXT Trading Executor Configuration
ccxt_executor_config:
  max_position_size: 0.1
  max_daily_trades: 100
  slippage_tolerance: 0.001
  order_timeout: 30.0
  exchanges:
    - name: "coinbase"
      enabled: true
      api_key_env: "COINBASE_API_KEY"
      secret_env: "COINBASE_SECRET"
      sandbox: false
    - name: "binance"
      enabled: true
      api_key_env: "BINANCE_API_KEY"
      secret_env: "BINANCE_SECRET"
      sandbox: false

# Order Book Manager Configuration
order_book_manager_config:
  max_levels: 20
  update_interval: 1.0
  enable_historical_tracking: true
  liquidity_threshold: 0.001

# Trading Strategy Executor Configuration
trading_strategy_executor_config:
  max_position_size: 0.1
  max_daily_trades: 100
  max_drawdown: 0.15
  risk_per_trade: 0.02
  enable_real_trading: false  # Set to true for live trading
  slippage_tolerance: 0.001
  execution_timeout: 30.0
  trading_symbols: ["BTC/USDC", "ETH/USDC"] 