# Schwabot Configuration Settings
# Version: v0.42f
# CLI and Fault Handling Configuration

cli:
  # CLI compatibility settings
  emoji: false                    # Enable/disable emoji usage
  verbose: true                   # Enable verbose output
  mode: "safe"                    # CLI mode: "safe", "full", "minimal"
  unicode_fallback: true          # Enable Unicode fallbacks
  windows_detection: true         # Enable Windows CLI detection
  
  # Output formatting
  timestamp_format: "%Y-%m-%d %H:%M:%S"
  log_level: "INFO"
  color_output: false             # Enable colored output where supported
  
  # Error handling
  safe_error_formatting: true
  error_context: true
  stack_trace: false

fault_handling:
  # Fault bus configuration
  enabled: true
  severity_threshold: 0.5
  max_queue_size: 1000
  memory_log_size: 10000
  
  # Fault correlation
  profit_correlation: true
  temporal_analysis: true
  recursive_detection: true
  
  # Fault types
  thermal_monitoring: true
  profit_monitoring: true
  bitmap_monitoring: true
  gpu_monitoring: true

system:
  # Core system settings
  debug_mode: false
  production_mode: true
  log_rotation: true
  backup_enabled: true
  
  # Performance settings
  async_threshold: 0.5
  max_concurrent_tasks: 10
  memory_limit_mb: 1024
  
  # Integration settings
  dlt_engine_enabled: true
  riddle_engine_enabled: true
  multi_bit_engine_enabled: true
  temporal_corrector_enabled: true

trading:
  # Trading system configuration
  demo_mode: true
  live_trading: false
  risk_management: true
  
  # Strategy settings
  default_strategy: "balanced_growth"
  strategy_rotation: true
  profit_target: 100.0
  
  # Market data
  price_update_interval: 1.0
  volume_analysis: true
  volatility_tracking: true

logging:
  # Logging configuration
  file_logging: true
  console_logging: true
  log_directory: "logs"
  
  # Log levels
  default_level: "INFO"
  fault_level: "WARNING"
  trading_level: "INFO"
  system_level: "DEBUG"
  
  # Log formats
  file_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_format: "%(levelname)s: %(message)s"

security:
  # Security settings
  api_key_encryption: true
  secure_connections: true
  audit_logging: true
  
  # Access control
  admin_only: false
  read_only_mode: false

monitoring:
  # System monitoring
  health_checks: true
  performance_monitoring: true
  alerting: true
  
  # Metrics
  metrics_collection: true
  metrics_interval: 60
  dashboard_enabled: true

development:
  # Development settings
  hot_reload: false
  test_mode: false
  profiling: false
  
  # Code quality
  linting: true
  type_checking: true
  documentation: true 