# Validation Framework Configuration
# ===============================

# Mathematical Validation Parameters
mathematical_validation:
  kalman_filter:
    max_prediction_error: 2.0
    min_confidence: 0.8
    process_noise: 0.01
    measurement_noise: 0.1
    
  utility_function:
    min_derivative: 0.0
    min_second_derivative: 0.0
    test_points: 10
    convergence_threshold: 1e-6
    
  convergence_analysis:
    max_iterations: 1000
    residual_threshold: 1e-6
    stability_threshold: 0.01
    divergence_threshold: 1e3

# Sequence Validation Parameters
sequence_validation:
  timing:
    max_latency_ms: 100
    min_interval_ms: 50
    max_sequence_duration_s: 3600
    timeout_threshold_ms: 5000
    
  dependencies:
    max_dependency_depth: 5
    cycle_detection_enabled: true
    deadlock_timeout_ms: 1000
    retry_attempts: 3
    
  ordering:
    strict_ordering: true
    allow_parallel_execution: false
    max_parallel_sequences: 1
    sequence_priority_levels: 3

# Error Handling Parameters
error_handling:
  mathematical:
    zero_division_handling: "return_zero"
    overflow_handling: "clamp"
    underflow_handling: "clamp"
    nan_handling: "replace_with_zero"
    
  recovery:
    max_recovery_attempts: 3
    recovery_timeout_ms: 1000
    state_persistence: true
    rollback_enabled: true
    
  validation:
    input_validation_strict: true
    type_checking_enabled: true
    range_validation_enabled: true
    null_handling: "reject"

# Performance Monitoring
performance_monitoring:
  enabled: true
  sampling_interval_ms: 1000
  metrics_retention_hours: 24
  alert_thresholds:
    cpu_usage_percent: 80
    memory_usage_percent: 80
    latency_ms: 100
    error_rate_percent: 1.0

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "validation_framework.log"
  max_size_mb: 100
  backup_count: 5
  console_output: true

# Integration Settings
integration:
  test_mode: true
  mock_external_services: true
  simulation_speed_multiplier: 1.0
  random_seed: 42
  debug_mode: false 