repos:

- repo: local
  hooks:
    - id: no-null-bytes
      name: "Reject files containing ASCII NUL (\\x00)"
      entry: python -c "import sys, pathlib; bad=[str(p) for p in pathlib.Path('.').rglob('*.py') if b'\\0' in p.read_bytes()]; print('\n'.join(bad)); sys.exit(bool(bad))"
      language: system
      types: [python]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      stages: [commit] 