# Bit Strategy Configuration for Schwabot
# ======================================
# Configuration for 4-bit/8-bit strategy logic and related systems

bit_strategy:
  # 4-bit Strategy Configuration
  four_bit:
    enabled: true
    strategy_count: 16
    asset_preferences:
      BTC: [4, 10, 12, 15]  # Volatility + phase history
      ETH: [3, 6, 13]       # ETH flips BTC, dynamic recognition
      XRP: [7, 8, 12]       # Entropy compression ‚Üí recursive logic
      USDC: [1, 5, 11]      # Profit exit, rebuy accumulation
      SOL: [7, 12, 9]       # High ghost entry activity
      RANDOM: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    
    strategy_definitions:
      0: "IDLE_NO_TRADE"
      1: "BASIC_DCA_ENTRY"
      2: "PHANTOM_DETECTOR_LOGIC"
      3: "VAULT_REBUY_SIGNAL"
      4: "EXIT_ON_VOL_SPIKE"
      5: "USDC_HARD_FLIP"
      6: "BTC_ETH_ROTATOR"
      7: "SOL_BOOST_GHOST_ENTRY"
      8: "XRP_COMPRESSION_BOUNCE"
      9: "RANDOM_REBALANCE_PULSE"
      10: "LONG_HOLD_DELAY_FLIP"
      11: "REVERSE_PHANTOM"
      12: "GHOST_LADDER_START"
      13: "MULTI_ASSET_SWAP_LOGIC"
      14: "RISK_OFFSET_GRADIENT_HOLD"
      15: "WARP_ECHO_RECURSIVE_ENGAGE"

  # 8-bit Microstrategy Configuration
  eight_bit:
    enabled: true
    microstrategy_count: 256
    hash_method: "sha256"
    entropy_integration: true
    drift_bits_enabled: true
    random_stream_size: 128
    
    micro_patterns:
      - "VOL_ENTRY_PULSE"
      - "BUYBACK_DELAY"
      - "MICROREBALANCE_INVERSION"
      - "WARP_LADDER_STAGE"
      - "PHANTOM_HOLD"
      - "PROFIT_CYCLE"
      - "ENTROPY_QUANTUM"
      - "PHASE_ROTATION"
      - "VAULT_ECHO"
      - "GHOST_MIRROR"
      - "DRIFT_COMPENSATION"
      - "ORBITAL_SYNC"

  # Strategy Expansion Modes
  expansion_modes:
    random:
      enabled: true
      max_strategies: 256
      seed_based: true
    
    ferris_wheel:
      enabled: true
      increment: 127
      cycle_length: 16
    
    phantom:
      enabled: true
      entropy_xor: true
      phantom_boost: 1.2
    
    vault:
      enabled: true
      multiplicative: true
      vault_factor: 1.0
    
    orbital:
      enabled: true
      sine_wave: true
      amplitude: 0.5

# Entropy Decay System Configuration
entropy_decay:
  enabled: true
  lambda_decay: 0.1
  phantom_boost: 1.5
  cleanup_threshold: 0.01
  max_signals: 1000
  decay_mode: "exponential"  # exponential, linear, stepped, adaptive
  half_life_seconds: 3600
  
  asset_decay_rates:
    BTC: 1.0
    ETH: 1.1
    XRP: 0.9
    USDC: 0.8
    SOL: 1.2
    RANDOM: 1.0
  
  asset_half_lives:
    BTC: 3600
    ETH: 3240
    XRP: 4320
    USDC: 5400
    SOL: 2880
    RANDOM: 3600

# Symbolic Registry Configuration
symbolic_registry:
  enabled: true
  auto_load_defaults: true
  config_file: "symbols.json"
  export_format: "json"
  
  symbol_categories:
    gradient: ["‚àá", "‚àÇ"]
    phase: ["Œ©", "Œ¶"]
    entropy: ["Œª", "ŒîS", "ùìî"]
    operator: ["Œ£", "‚Ñß"]
    function: ["œà", "C(t)", "Œ∫", "Œû", "ùïè"]
  
  cli_enabled: true
  search_enabled: true
  export_enabled: true

# Vault-Orbital Bridge Configuration
vault_orbital_bridge:
  enabled: true
  automatic_transitions: true
  transition_threshold: 0.7
  
  liquidity_thresholds:
    empty: 0.0
    low: 0.2
    stable: 0.5
    high: 0.8
    overflow: 1.0
  
  entropy_thresholds:
    s: 0.1
    p: 0.3
    d: 0.5
    f: 0.8
    null: 1.0
  
  strategy_mappings:
    overflow_f: "full_sweep_exit"
    high_d: "partial_profit_take"
    stable_s: "hold_maintain"
    low_p: "accumulate_dca"
    empty_null: "emergency_recovery"
    phantom_f: "phantom_hold"
    locked_s: "wait_unlock"
  
  state_mappings:
    - vault_state: "overflow"
      orbital_state: "f"
      transition_probability: 0.9
      strategy_trigger: "full_sweep_exit"
      liquidity_threshold: 0.95
      entropy_threshold: 0.8
    
    - vault_state: "high"
      orbital_state: "d"
      transition_probability: 0.7
      strategy_trigger: "partial_profit_take"
      liquidity_threshold: 0.8
      entropy_threshold: 0.5
    
    - vault_state: "stable"
      orbital_state: "s"
      transition_probability: 0.8
      strategy_trigger: "hold_maintain"
      liquidity_threshold: 0.5
      entropy_threshold: 0.1
    
    - vault_state: "low"
      orbital_state: "p"
      transition_probability: 0.6
      strategy_trigger: "accumulate_dca"
      liquidity_threshold: 0.2
      entropy_threshold: 0.3
    
    - vault_state: "empty"
      orbital_state: "null"
      transition_probability: 0.5
      strategy_trigger: "emergency_recovery"
      liquidity_threshold: 0.0
      entropy_threshold: 1.0
    
    - vault_state: "phantom"
      orbital_state: "f"
      transition_probability: 0.8
      strategy_trigger: "phantom_hold"
      liquidity_threshold: 0.3
      entropy_threshold: 0.9
    
    - vault_state: "locked"
      orbital_state: "s"
      transition_probability: 0.1
      strategy_trigger: "wait_unlock"
      liquidity_threshold: 0.0
      entropy_threshold: 0.0

# Performance Configuration
performance:
  cache_enabled: true
  cache_size: 1024
  cache_ttl: 3600
  memory_efficient: true
  parallel_processing: true
  
  optimization:
    precompute_bitmaps: true
    hash_caching: true
    strategy_lookup_optimization: true
    entropy_calculation_optimization: true

# Integration Configuration
integration:
  # Integration with existing systems
  symbolic_math_interface: true
  strategy_bit_mapper: true
  entropy_decay_system: true
  vault_orbital_bridge: true
  symbolic_registry: true
  
  # External system integrations
  phantom_detector: true
  hash_registry: true
  btc_signal_router: true
  entropy_layer: true
  vault_logic: true
  profit_cycle_allocator: true

# Monitoring and Logging
monitoring:
  enable_metrics: true
  enable_statistics: true
  log_level: "INFO"
  performance_monitoring: true
  
  metrics:
    strategy_classification_time: true
    entropy_decay_cleanup_count: true
    vault_orbital_transitions: true
    symbolic_operator_usage: true
    cache_hit_ratio: true

# Validation Configuration
validation:
  enable_input_validation: true
  enable_output_validation: true
  enable_state_validation: true
  
  thresholds:
    min_confidence: 0.5
    max_entropy: 10.0
    min_liquidity: 0.0
    max_liquidity: 1.0
    min_volatility: 0.0
    max_volatility: 1.0

# Error Handling
error_handling:
  enable_exception_logging: true
  enable_error_recovery: true
  max_retry_attempts: 3
  retry_delay: 1.0
  enable_graceful_degradation: true
  log_error_details: true
  
  fallback_strategies:
    classification_failure: "hold_maintain"
    decay_calculation_failure: "use_initial_weight"
    bridge_failure: "stable_s"
    registry_failure: "use_default_symbols" 