# Connectivity Hooks and State Definitions for Mathematical Relay System
# Defines all state forms, algebraic connectivity, and measurement hooks

state_forms:
  - name: small_form
    description: Minimal state, low memory, fast switching
    algebraic_type: compact
    default: true
  - name: large_form
    description: Maximal state, high memory, full tensor
    algebraic_type: expanded
  - name: midform
    description: Median state, balanced memory and speed
    algebraic_type: median
  - name: compact
    description: Highly compressed, for rapid switching
    algebraic_type: compact
  - name: gated
    description: State with access gating, for security or throttling
    algebraic_type: gated
  - name: tall
    description: Elongated state, for long timeframes or deep memory
    algebraic_type: elongated
  - name: looped
    description: Cyclic state, for periodic or oscillatory processes
    algebraic_type: cyclic
  - name: oblong
    description: Asymmetric, for non-uniform or skewed processes
    algebraic_type: oblong

algebraic_connectivity:
  - name: sha256_state
    description: 256-bit SHA state for secure hashing and relay
    function: sha256
  - name: mean
    description: Arithmetic mean of state values
    function: mean
  - name: median
    description: Median of state values
    function: median
  - name: deviation
    description: Standard deviation of state values
    function: std
  - name: frequency_ratio
    description: Frequency ratio for state switching
    function: frequency_ratio
  - name: pool_valuation
    description: Pool valuation for missing or hanging states
    function: pool_valuation
  - name: apr
    description: Annual Percentage Rate for portfolio value
    function: apr

handoff_definitions:
  - name: state_start
    description: State initialization and entry
  - name: state_end
    description: State completion and exit
  - name: state_middle
    description: Median or mid-point state
  - name: state_measurement
    description: Measurement and logging of state
  - name: state_render
    description: Rendering state for visualization
  - name: state_compute
    description: Computation and transformation of state
  - name: state_switch
    description: Switching between state forms
  - name: state_adapt
    description: Adapting state to new conditions
  - name: state_connect
    description: API or mathematical plumbing connection 