# Secure API Integration Configuration
# ===================================
# Comprehensive configuration for secure API integration with Alpha256 encryption,
# multi-exchange profile management, and intelligent rebalancing.

version: "2.0.0"
created_at: "2025-01-18"
description: "Secure API integration configuration with Alpha256 encryption and multi-exchange support"

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

security:
  # Alpha256 Encryption Settings
  encryption_enabled: true
  key_rotation_interval: 86400  # 24 hours
  max_failed_attempts: 3
  session_timeout: 3600  # 1 hour
  audit_logging: true
  
  # API Key Management
  key_storage_path: "config/keys"
  key_encryption_level: "alpha256"
  auto_key_rotation: true
  key_backup_enabled: true
  
  # Security Headers
  require_signature: true
  require_timestamp: true
  require_nonce: true
  max_request_age: 300  # 5 minutes
  
  # Rate Limiting
  rate_limit_enabled: true
  rate_limit_window: 60  # 1 minute
  rate_limit_max_requests: 100

# =============================================================================
# EXCHANGE CONFIGURATIONS
# =============================================================================

exchanges:
  coinbase:
    enabled: true
    sandbox: true
    rate_limit: 100  # requests per minute
    timeout: 30  # seconds
    websocket_enabled: true
    retry_attempts: 3
    retry_delay: 5  # seconds
    
  binance:
    enabled: true
    sandbox: true
    rate_limit: 1200  # requests per minute
    timeout: 30  # seconds
    websocket_enabled: true
    retry_attempts: 3
    retry_delay: 5  # seconds
    
  kraken:
    enabled: true
    sandbox: false  # Kraken doesn't have sandbox
    rate_limit: 15  # requests per 15 seconds
    timeout: 30  # seconds
    websocket_enabled: true
    retry_attempts: 3
    retry_delay: 5  # seconds

# =============================================================================
# PROFILE CONFIGURATIONS
# =============================================================================

profiles:
  # Profile A - Conservative Trading
  profile_a:
    name: "Conservative Trading Profile"
    exchange: "coinbase"
    type: "conservative"
    api_key_id: "coinbase_profile_a_key"
    enabled: true
    sandbox: true
    max_position_size: 0.05  # 5% of portfolio
    rebalancing_strategy: "threshold_based"
    rebalancing_threshold: 0.03  # 3% deviation
    randomization_factor: 0.05  # 5% randomization
    
    target_allocation:
      BTC: 0.40  # 40% Bitcoin
      ETH: 0.30  # 30% Ethereum
      USDC: 0.20  # 20% Stablecoin
      SOL: 0.05  # 5% Solana
      XRP: 0.05  # 5% Ripple
    
    strategy_weights:
      volume_weighted_hash_oscillator: 0.40
      zygot_zalgo_entropy_dual_key_gate: 0.30
      multi_phase_strategy_weight_tensor: 0.20
      quantum_strategy_calculator: 0.10
    
    risk_parameters:
      max_drawdown: 0.10  # 10% max drawdown
      volatility_target: 0.15  # 15% volatility target
      correlation_limit: 0.70  # 70% correlation limit
  
  # Profile B - Moderate Trading
  profile_b:
    name: "Moderate Trading Profile"
    exchange: "binance"
    type: "moderate"
    api_key_id: "binance_profile_b_key"
    enabled: true
    sandbox: true
    max_position_size: 0.10  # 10% of portfolio
    rebalancing_strategy: "risk_adjusted"
    rebalancing_threshold: 0.05  # 5% deviation
    randomization_factor: 0.10  # 10% randomization
    
    target_allocation:
      BTC: 0.35  # 35% Bitcoin
      ETH: 0.25  # 25% Ethereum
      SOL: 0.15  # 15% Solana
      XRP: 0.10  # 10% Ripple
      USDC: 0.15  # 15% Stablecoin
    
    strategy_weights:
      volume_weighted_hash_oscillator: 0.30
      zygot_zalgo_entropy_dual_key_gate: 0.25
      multi_phase_strategy_weight_tensor: 0.25
      quantum_strategy_calculator: 0.15
      entropy_enhanced_trading_executor: 0.05
    
    risk_parameters:
      max_drawdown: 0.15  # 15% max drawdown
      volatility_target: 0.20  # 20% volatility target
      correlation_limit: 0.60  # 60% correlation limit
  
  # Profile C - Aggressive Trading
  profile_c:
    name: "Aggressive Trading Profile"
    exchange: "kraken"
    type: "aggressive"
    api_key_id: "kraken_profile_c_key"
    enabled: true
    sandbox: false
    max_position_size: 0.15  # 15% of portfolio
    rebalancing_strategy: "momentum_driven"
    rebalancing_threshold: 0.08  # 8% deviation
    randomization_factor: 0.15  # 15% randomization
    
    target_allocation:
      BTC: 0.30  # 30% Bitcoin
      ETH: 0.20  # 20% Ethereum
      SOL: 0.20  # 20% Solana
      XRP: 0.15  # 15% Ripple
      USDC: 0.15  # 15% Stablecoin
    
    strategy_weights:
      volume_weighted_hash_oscillator: 0.25
      zygot_zalgo_entropy_dual_key_gate: 0.20
      multi_phase_strategy_weight_tensor: 0.30
      quantum_strategy_calculator: 0.15
      entropy_enhanced_trading_executor: 0.10
    
    risk_parameters:
      max_drawdown: 0.25  # 25% max drawdown
      volatility_target: 0.30  # 30% volatility target
      correlation_limit: 0.50  # 50% correlation limit
  
  # Profile D - Arbitrage Trading
  profile_d:
    name: "Arbitrage Trading Profile"
    exchange: "coinbase"
    type: "arbitrage"
    api_key_id: "coinbase_profile_d_key"
    enabled: true
    sandbox: true
    max_position_size: 0.20  # 20% of portfolio
    rebalancing_strategy: "volatility_targeted"
    rebalancing_threshold: 0.02  # 2% deviation
    randomization_factor: 0.02  # 2% randomization
    
    target_allocation:
      BTC: 0.25  # 25% Bitcoin
      ETH: 0.25  # 25% Ethereum
      SOL: 0.20  # 20% Solana
      XRP: 0.15  # 15% Ripple
      USDC: 0.15  # 15% Stablecoin
    
    strategy_weights:
      volume_weighted_hash_oscillator: 0.20
      zygot_zalgo_entropy_dual_key_gate: 0.15
      multi_phase_strategy_weight_tensor: 0.25
      quantum_strategy_calculator: 0.25
      entropy_enhanced_trading_executor: 0.15
    
    risk_parameters:
      max_drawdown: 0.05  # 5% max drawdown
      volatility_target: 0.10  # 10% volatility target
      correlation_limit: 0.80  # 80% correlation limit

# =============================================================================
# REBALANCING CONFIGURATION
# =============================================================================

rebalancing:
  enabled: true
  check_interval: 300  # 5 minutes
  max_deviation: 0.10  # 10% maximum deviation
  randomization_enabled: true
  randomization_factor: 0.10  # 10% randomization
  
  # Rebalancing Strategies
  strategies:
    threshold_based:
      enabled: true
      min_threshold: 0.02  # 2% minimum threshold
      max_threshold: 0.15  # 15% maximum threshold
    
    time_based:
      enabled: true
      interval: 3600  # 1 hour
      max_frequency: 300  # 5 minutes minimum between checks
    
    risk_adjusted:
      enabled: true
      volatility_weight: 0.3
      correlation_weight: 0.2
      momentum_weight: 0.5
    
    volatility_targeted:
      enabled: true
      target_volatility: 0.15  # 15% target volatility
      volatility_window: 252  # 1 year (trading days)
    
    momentum_driven:
      enabled: true
      momentum_window: 20  # 20 days
      momentum_threshold: 0.05  # 5% momentum threshold
  
  # Execution Settings
  execution:
    max_slippage: 0.001  # 0.1% maximum slippage
    min_order_size: 10.0  # $10 minimum order size
    max_order_size: 10000.0  # $10,000 maximum order size
    order_timeout: 30  # 30 seconds
    retry_failed_orders: true
    max_retry_attempts: 3

# =============================================================================
# PORTFOLIO CONFIGURATION
# =============================================================================

portfolio:
  # Concentration Limits
  max_concentration: 0.25  # 25% maximum in any single asset
  min_diversification: 3  # Minimum 3 assets
  max_correlation: 0.70  # 70% maximum correlation between assets
  
  # Target Assets
  target_assets:
    - BTC
    - ETH
    - SOL
    - XRP
    - USDC
  
  # Excluded Assets (avoid over-concentration)
  excluded_assets:
    - USDT  # Avoid stablecoin concentration
    - BUSD
    - DAI
  
  # Asset Categories
  asset_categories:
    large_cap:
      - BTC
      - ETH
      max_allocation: 0.40
    mid_cap:
      - SOL
      - XRP
      max_allocation: 0.20
    stablecoins:
      - USDC
      max_allocation: 0.30
  
  # Risk Management
  risk_management:
    max_drawdown: 0.20  # 20% maximum drawdown
    stop_loss_enabled: true
    stop_loss_percentage: 0.05  # 5% stop loss
    take_profit_enabled: true
    take_profit_percentage: 0.10  # 10% take profit

# =============================================================================
# PERFORMANCE MONITORING
# =============================================================================

performance:
  # Metrics Tracking
  track_metrics: true
  metrics_interval: 60  # 1 minute
  store_history: true
  history_retention_days: 365  # 1 year
  
  # Performance Targets
  targets:
    annual_return: 0.15  # 15% annual return
    sharpe_ratio: 1.5
    max_drawdown: 0.10  # 10% maximum drawdown
    volatility: 0.15  # 15% volatility
  
  # Alerts
  alerts:
    enabled: true
    drawdown_alert: 0.05  # Alert at 5% drawdown
    performance_alert: 0.10  # Alert at 10% underperformance
    volatility_alert: 0.25  # Alert at 25% volatility

# =============================================================================
# LOGGING AND MONITORING
# =============================================================================

logging:
  level: "INFO"
  file_enabled: true
  file_path: "logs/secure_api.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  
  # Security Logging
  security_logging:
    enabled: true
    log_api_calls: true
    log_encryption_events: true
    log_security_violations: true
    log_balance_changes: true
  
  # Performance Logging
  performance_logging:
    enabled: true
    log_trade_executions: true
    log_rebalancing_actions: true
    log_portfolio_changes: true

# =============================================================================
# SYSTEM CONFIGURATION
# =============================================================================

system:
  # Startup Settings
  auto_start: true
  health_check_interval: 60  # 1 minute
  graceful_shutdown: true
  shutdown_timeout: 30  # 30 seconds
  
  # Resource Limits
  max_memory_usage: 1073741824  # 1GB
  max_cpu_usage: 0.8  # 80%
  max_concurrent_requests: 100
  
  # Backup and Recovery
  backup_enabled: true
  backup_interval: 3600  # 1 hour
  backup_retention_days: 7
  auto_recovery: true

# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================

# Environment variable mappings for API keys
environment_mappings:
  coinbase_profile_a_key: "COINBASE_PROFILE_A_API_KEY"
  coinbase_profile_a_secret: "COINBASE_PROFILE_A_SECRET"
  coinbase_profile_a_passphrase: "COINBASE_PROFILE_A_PASSPHRASE"
  
  binance_profile_b_key: "BINANCE_PROFILE_B_API_KEY"
  binance_profile_b_secret: "BINANCE_PROFILE_B_SECRET"
  
  kraken_profile_c_key: "KRAKEN_PROFILE_C_API_KEY"
  kraken_profile_c_secret: "KRAKEN_PROFILE_C_SECRET"

# =============================================================================
# VALIDATION RULES
# =============================================================================

validation:
  # Configuration Validation
  validate_on_startup: true
  strict_mode: true
  
  # API Key Validation
  validate_api_keys: true
  test_api_connections: true
  
  # Portfolio Validation
  validate_allocations: true
  check_concentration_limits: true
  verify_asset_support: true 