bit_depths:
- depth: 4
  max_operations: 1000
  memory_limit: 0.5
  profit_threshold: 0.1
  thermal_threshold: 70.0
- depth: 8
  max_operations: 500
  memory_limit: 0.6
  profit_threshold: 0.2
  thermal_threshold: 65.0
- depth: 16
  max_operations: 250
  memory_limit: 0.7
  profit_threshold: 0.3
  thermal_threshold: 60.0
- depth: 42
  max_operations: 50
  memory_limit: 0.8
  profit_threshold: 0.4
  thermal_threshold: 55.0
- depth: 81
  max_operations: 10
  memory_limit: 0.9
  profit_threshold: 0.5
  thermal_threshold: 50.0
devices:
  gpu_ids:
  - 0
  memory_limit: 0.5
  temperature_threshold: 80.0
  utilization_threshold: 0.9
environment:
  debug_mode: false
  force_cpu: false
  profiling_enabled: true
faults:
  error_threshold: 3
  max_retries: 3
  retry_delay: 1.0
  timeout: 30.0
gpu_safety:
  batch_size: 1000
  max_temperature: 75.0
  max_utilization: 0.8
  memory_pool_size: 512
  min_data_size: 1000
  stream_pool_size: 4
  sync_interval: 100
logging:
  file: logs/gpu_offload.log
  level: INFO
  metrics_file: logs/gpu_metrics.json
  profile_file: logs/gpu_profile.json
profit:
  history_window: 1000
  min_profit_threshold: 0.2
  profit_decay: 0.95
  thermal_weight: 0.3
thermal:
  efficiency_threshold: 0.5
  max_temp: 85.0
  optimal_temp: 60.0
  thermal_decay: 0.95
