# Schwabot Core Configuration
# Version: v1.0.0
# Recursive Unicode Pathway Stacking & Mathematical Engine Integration

# Core System Architecture
system:
  name: "Schwabot"
  version: "1.0.0"
  mode: "production"  # production, development, testing
  debug_level: "INFO"
  
  # Recursive Unicode Pathway Configuration
  unicode_pathways:
    enabled: true
    max_recursion_depth: 16
    pathway_cache_size: 10000
    hash_algorithm: "sha256"
    bit_depth: 8  # 4-bit, 8-bit, 16-bit, 32-bit, 64-bit
    
    # Recursive stacking parameters
    stacking:
      max_layers: 8
      layer_weight_decay: 0.85
      cross_layer_validation: true
      memory_persistence: true
      
    # Unicode symbol mappings
    symbols:
      profit_trigger: "💰"
      sell_signal: "💸"
      volatility_high: "🔥"
      fast_execution: "⚡"
      target_hit: "🎯"
      recursive_entry: "🔄"
      uptrend: "📈"
      downtrend: "📉"
      ai_logic: "[BRAIN]"
      prediction: "🔮"
      high_confidence: "⭐"
      risk_warning: "⚠️"
      stop_loss: "🛑"
      go_signal: "🟢"
      stop_signal: "🔴"
      wait_signal: "🟡"

# Mathematical Engine Configuration
mathematical_engines:
  # ALEPH - Advanced Logic Engine for Profit Harmonization
  aleph:
    enabled: true
    version: "2.1.0"
    memory_size: 10000
    learning_rate: 0.001
    confidence_threshold: 0.75
    
    # ALEPH mathematical parameters
    parameters:
      profit_harmonization_factor: 1.2
      temporal_weighting: 0.8
      volatility_sensitivity: 1.1
      risk_adjustment_rate: 0.9
      
    # ALEPH neural pathways
    neural_pathways:
      input_layer_size: 256
      hidden_layer_size: 128
      output_layer_size: 64
      activation_function: "relu"
      dropout_rate: 0.2

  # ALIF - Advanced Logic Integration Framework
  alif:
    enabled: true
    version: "1.8.0"
    integration_mode: "adaptive"
    cross_engine_sync: true
    
    # ALIF integration parameters
    parameters:
      integration_weight: 0.6
      cross_correlation_threshold: 0.7
      adaptive_learning_rate: 0.005
      stability_factor: 0.85
      
    # ALIF framework components
    components:
      profit_router: true
      risk_manager: true
      signal_processor: true
      memory_manager: true

  # RITTLE - Recursive Interlocking Dimensional Logic
  rittle:
    enabled: true
    version: "3.0.0"
    dimensional_layers: 4
    recursive_depth: 8
    
    # RITTLE dimensional parameters
    parameters:
      dimensional_weight: 0.7
      recursive_factor: 1.1
      interlocking_strength: 0.8
      stability_threshold: 0.6
      
    # RITTLE logic gates
    logic_gates:
      and_gate: true
      or_gate: true
      xor_gate: true
      nand_gate: true
      nor_gate: true

  # RIDDLE - Recursive Interlocking Drift Logic Engine
  riddle:
    enabled: true
    version: "2.5.0"
    drift_resolution: 0.001
    temporal_window: 1000
    
    # RIDDLE drift parameters
    parameters:
      drift_sensitivity: 1.0
      temporal_weight: 0.9
      volatility_factor: 1.2
      mean_reversion_strength: 0.7
      
    # RIDDLE drift components
    components:
      drift_detector: true
      temporal_analyzer: true
      volatility_calculator: true
      mean_reversion_engine: true

  # Ferris RDE - Ferris Wheel Rotational Drift Engine
  ferris_rde:
    enabled: true
    version: "1.9.0"
    rotational_speed: 1.0
    drift_amplitude: 0.5
    
    # Ferris RDE parameters
    parameters:
      rotation_factor: 1.1
      drift_magnitude: 0.8
      centrifugal_force: 0.6
      gravitational_pull: 0.9
      
    # Ferris RDE components
    components:
      rotation_engine: true
      drift_calculator: true
      centrifugal_analyzer: true
      gravitational_sensor: true

# Profit Tier Navigation System
profit_tier_navigation:
  enabled: true
  version: "2.0.0"
  
  # Tier definitions
  tiers:
    tier_1:
      name: "Ultra Conservative"
      risk_level: 0.1
      profit_target: 0.5
      max_drawdown: 0.1
      volume_multiplier: 0.5
      
    tier_2:
      name: "Conservative"
      risk_level: 0.2
      profit_target: 1.0
      max_drawdown: 0.2
      volume_multiplier: 0.7
      
    tier_3:
      name: "Balanced"
      risk_level: 0.4
      profit_target: 2.0
      max_drawdown: 0.3
      volume_multiplier: 1.0
      
    tier_4:
      name: "Aggressive"
      risk_level: 0.6
      profit_target: 3.0
      max_drawdown: 0.4
      volume_multiplier: 1.3
      
    tier_5:
      name: "Ultra Aggressive"
      risk_level: 0.8
      profit_target: 5.0
      max_drawdown: 0.5
      volume_multiplier: 1.5

  # Navigation parameters
  navigation:
    auto_tier_adjustment: true
    tier_transition_threshold: 0.1
    memory_based_selection: true
    performance_weighting: 0.7
    risk_adjustment_rate: 0.05

# Backchannel Information System
backchannel:
  enabled: true
  version: "1.5.0"
  
  # Information storage
  storage:
    type: "json"  # json, sqlite, redis
    file_path: "backchannel/memory_stack"
    max_file_size: "100MB"
    compression: true
    encryption: false
    
  # State management
  states:
    save_interval: 60  # seconds
    max_states: 10000
    state_compression: true
    
  # Information categories
  categories:
    profit_states: true
    market_conditions: true
    engine_performance: true
    error_logs: true
    trading_decisions: true
    memory_patterns: true

# CPU/GPU Utilization Mapping
resource_utilization:
  enabled: true
  version: "1.2.0"
  
  # CPU configuration
  cpu:
    max_threads: 8
    thread_priority: "normal"
    affinity_mapping: true
    load_balancing: true
    
    # CPU allocation
    allocation:
      mathematical_engines: 0.4
      profit_navigation: 0.2
      backchannel_processing: 0.1
      api_handling: 0.2
      monitoring: 0.1
      
  # GPU configuration
  gpu:
    enabled: true
    device_id: 0
    memory_limit: "4GB"
    compute_capability: "7.5"
    
    # GPU allocation
    allocation:
      neural_networks: 0.5
      matrix_operations: 0.3
      hash_computations: 0.2
      
  # Performance monitoring
  monitoring:
    enabled: true
    metrics_interval: 5  # seconds
    alert_threshold: 0.9
    auto_scaling: true

# Trading Integration
trading:
  enabled: true
  version: "2.1.0"
  
  # CCXT Integration
  ccxt:
    enabled: true
    exchanges:
      - "binance"
      - "coinbase"
      - "kraken"
      - "kucoin"
      
    # CCXT parameters
    parameters:
      rate_limit: true
      timeout: 30000
      retry_on_error: true
      max_retries: 3
      
  # Coinbase Integration
  coinbase:
    enabled: true
    api_version: "v2"
    sandbox_mode: false
    
    # Coinbase parameters
    parameters:
      order_type: "market"
      time_in_force: "GTC"
      post_only: false
      
  # Trading parameters
  parameters:
    default_strategy: "balanced_growth"
    risk_management: true
    stop_loss_percentage: 0.02
    take_profit_percentage: 0.05
    max_position_size: 0.1
    min_volume_threshold: 1000
    
  # Volume and stop loss
  volume_management:
    enabled: true
    volume_analysis: true
    dynamic_position_sizing: true
    volume_threshold: 1000
    
  stop_loss:
    enabled: true
    trailing_stop: true
    stop_loss_percentage: 0.02
    max_drawdown: 0.1

# API Integration
api:
  enabled: true
  version: "1.8.0"
  
  # Flask server
  flask:
    enabled: true
    host: "localhost"
    port: 5000
    debug: false
    threaded: true
    
  # Vault Bus
  vault_bus:
    enabled: true
    bus_type: "redis"  # redis, rabbitmq, kafka
    host: "localhost"
    port: 6379
    
  # Internal API
  internal:
    enabled: true
    endpoints:
      - "/api/v1/profit"
      - "/api/v1/status"
      - "/api/v1/performance"
      - "/api/v1/configuration"
      
  # External API
  external:
    enabled: true
    rate_limiting: true
    authentication: true
    cors_enabled: true

# Memory and Learning
memory:
  enabled: true
  version: "1.6.0"
  
  # Memory types
  types:
    short_term:
      enabled: true
      size: 1000
      ttl: 3600  # seconds
      
    long_term:
      enabled: true
      size: 10000
      persistence: true
      
    pattern_memory:
      enabled: true
      size: 5000
      pattern_recognition: true
      
  # Learning parameters
  learning:
    enabled: true
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    validation_split: 0.2
    
  # Recursive improvement
  recursive_improvement:
    enabled: true
    improvement_threshold: 0.05
    max_iterations: 100
    convergence_tolerance: 0.001

# Visualization and Monitoring
visualization:
  enabled: true
  version: "1.3.0"
  
  # Dashboard
  dashboard:
    enabled: true
    port: 8080
    real_time_updates: true
    chart_library: "plotly"
    
  # Metrics
  metrics:
    enabled: true
    collection_interval: 5  # seconds
    storage_duration: "30d"
    
  # Alerts
  alerts:
    enabled: true
    channels:
      - "email"
      - "slack"
      - "webhook"
      
# Security
security:
  enabled: true
  version: "1.4.0"
  
  # Authentication
  authentication:
    enabled: true
    method: "jwt"
    token_expiry: 3600  # seconds
    
  # Encryption
  encryption:
    enabled: true
    algorithm: "AES-256"
    key_rotation: true
    
  # Access control
  access_control:
    enabled: true
    role_based: true
    admin_only_operations: true 