# Strategy Sustainment Validator Configuration
# ==========================================
# Configuration for the 8-principle sustainment framework validation

# Overall validation settings
overall_threshold: 0.75  # Minimum weighted score for strategy approval
confidence_threshold: 0.70  # Minimum confidence for execution

# Principle weights (importance multipliers)
# Higher weight = more important for overall score
weights:
  integration: 1.0      # System harmony and module alignment
  anticipation: 1.2     # Predictive capabilities (high importance)
  responsiveness: 1.2   # Real-time adaptation (high importance)
  simplicity: 0.8       # Lower complexity preference
  economy: 1.0          # Resource efficiency
  survivability: 1.5    # Risk management (critical)
  continuity: 1.3       # Persistent operation (important)
  transcendence: 2.0    # Emergent optimization (highest importance)

# Individual principle thresholds
# Minimum score required for each principle to pass
thresholds:
  integration: 0.75     # System integration quality
  anticipation: 0.70    # Predictive accuracy
  responsiveness: 0.80  # Speed of adaptation
  simplicity: 0.65      # Complexity management
  economy: 0.75         # Profit efficiency
  survivability: 0.85   # Risk management (highest threshold)
  continuity: 0.80      # Operational persistence
  transcendence: 0.70   # Emergent capabilities

# Critical principles that cause immediate failure if not met
critical_principles:
  - survivability  # Must pass for any strategy execution
  - economy        # Must be profitable to proceed

# Adaptive threshold configuration
adaptive_thresholds:
  enabled: true
  learning_rate: 0.01
  min_threshold: 0.30
  max_threshold: 0.95
  adjustment_frequency: 100  # Adjust every N validations

# Market condition modifiers
# Adjust validation based on market state
market_modifiers:
  high_volatility:
    survivability_bonus: 0.05    # Require higher survivability in volatile markets
    responsiveness_bonus: 0.03   # Need faster response
  
  low_volatility:
    economy_bonus: 0.02          # Can be more selective about profits
    
  thermal_stress:
    simplicity_bonus: 0.05       # Prefer simpler strategies under thermal stress
    integration_penalty: -0.02   # Integration may be compromised

# Fractal integration settings
fractal_integration:
  enabled: true
  coherence_weight: 0.3
  pattern_depth_weight: 0.2
  stability_weight: 0.5

# Thermal management integration
thermal_integration:
  enabled: true
  thermal_load_penalty: 0.1     # Penalty per unit thermal load
  cooling_bonus: 0.05           # Bonus when thermal load is low

# Confidence engine integration
confidence_config:
  stability_epsilon: 0.01
  lambda_min: 0.8
  lambda_max: 1.5
  confidence_threshold: 0.6
  adaptive_lambda: true

# Performance tracking
performance_tracking:
  enabled: true
  history_length: 1000
  trend_analysis_window: 10
  alert_thresholds:
    pass_rate_low: 0.60         # Alert if pass rate drops below 60%
    fail_rate_high: 0.30        # Alert if fail rate exceeds 30%
    
# Logging configuration
logging:
  level: INFO
  detailed_scoring: false       # Log detailed component scores
  recommendations: true         # Log recommendations for failed validations
  performance_summary: true     # Log periodic performance summaries

# Development and testing settings
development:
  mock_thermal_manager: true    # Use mock when thermal manager unavailable
  mock_fractal_core: false      # Use real fractal core
  debug_validation: false       # Extra debug output
  quick_validation_mode: false  # Simplified validation for testing 